// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: stubs/grpcc/task.proto

package grpcc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_deadline Priority = 0
	Priority_busy     Priority = 1
	Priority_started  Priority = 2
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "deadline",
		1: "busy",
		2: "started",
	}
	Priority_value = map[string]int32{
		"deadline": 0,
		"busy":     1,
		"started":  2,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_stubs_grpcc_task_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_stubs_grpcc_task_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_stubs_grpcc_task_proto_rawDescGZIP(), []int{0}
}

type Result int32

const (
	Result_Ok    Result = 0
	Result_Error Result = 1
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "Ok",
		1: "Error",
	}
	Result_value = map[string]int32{
		"Ok":    0,
		"Error": 1,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_stubs_grpcc_task_proto_enumTypes[1].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_stubs_grpcc_task_proto_enumTypes[1]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_stubs_grpcc_task_proto_rawDescGZIP(), []int{1}
}

type Create_Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskName  string   `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Deadline  string   `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	LevelWork Priority `protobuf:"varint,3,opt,name=level_work,json=levelWork,proto3,enum=grpcc.Priority" json:"level_work,omitempty"`
	Id        int64    `protobuf:"varint,4,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	Uid       string   `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Create_Task) Reset() {
	*x = Create_Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stubs_grpcc_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Create_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_Task) ProtoMessage() {}

func (x *Create_Task) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_grpcc_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_Task.ProtoReflect.Descriptor instead.
func (*Create_Task) Descriptor() ([]byte, []int) {
	return file_stubs_grpcc_task_proto_rawDescGZIP(), []int{0}
}

func (x *Create_Task) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *Create_Task) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *Create_Task) GetLevelWork() Priority {
	if x != nil {
		return x.LevelWork
	}
	return Priority_deadline
}

func (x *Create_Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Create_Task) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type Delete_Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskName string `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Uid      string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Delete_Task) Reset() {
	*x = Delete_Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stubs_grpcc_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete_Task) ProtoMessage() {}

func (x *Delete_Task) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_grpcc_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete_Task.ProtoReflect.Descriptor instead.
func (*Delete_Task) Descriptor() ([]byte, []int) {
	return file_stubs_grpcc_task_proto_rawDescGZIP(), []int{1}
}

func (x *Delete_Task) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *Delete_Task) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type View_Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViewTask *Create_Task `protobuf:"bytes,1,opt,name=view_task,json=viewTask,proto3" json:"view_task,omitempty"`
	Uid      string       `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *View_Task) Reset() {
	*x = View_Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stubs_grpcc_task_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *View_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View_Task) ProtoMessage() {}

func (x *View_Task) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_grpcc_task_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View_Task.ProtoReflect.Descriptor instead.
func (*View_Task) Descriptor() ([]byte, []int) {
	return file_stubs_grpcc_task_proto_rawDescGZIP(), []int{2}
}

func (x *View_Task) GetViewTask() *Create_Task {
	if x != nil {
		return x.ViewTask
	}
	return nil
}

func (x *View_Task) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result Result `protobuf:"varint,1,opt,name=result,proto3,enum=grpcc.Result" json:"result,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stubs_grpcc_task_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_stubs_grpcc_task_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_stubs_grpcc_task_proto_rawDescGZIP(), []int{3}
}

func (x *Status) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_Ok
}

var File_stubs_grpcc_task_proto protoreflect.FileDescriptor

var file_stubs_grpcc_task_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x74, 0x75, 0x62, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x63, 0x2f, 0x74, 0x61,
	0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x70, 0x63, 0x63, 0x22,
	0x98, 0x01, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x09, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x0b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x5f, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61,
	0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x09, 0x56, 0x69, 0x65, 0x77,
	0x5f, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x2f, 0x0a, 0x09, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x74, 0x61,
	0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x63,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x08, 0x76, 0x69,
	0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x2f, 0x0a, 0x08, 0x50, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x0c, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x62, 0x75, 0x73, 0x79, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10, 0x02, 0x2a, 0x1b, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x32, 0x34, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x5f,
	0x41, 0x64, 0x64, 0x12, 0x28, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0d,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x3a, 0x0a,
	0x0b, 0x54, 0x61, 0x73, 0x6b, 0x5f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x2b, 0x0a, 0x06,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x63, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x38, 0x0a, 0x0a, 0x4c, 0x69, 0x73,
	0x74, 0x5f, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x2a, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x63, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x5f, 0x54, 0x61, 0x73,
	0x6b, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x63, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x5f, 0x54,
	0x61, 0x73, 0x6b, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x6c, 0x69, 0x32, 0x32, 0x31, 0x30, 0x2f, 0x66, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x73, 0x74, 0x75, 0x62, 0x73,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stubs_grpcc_task_proto_rawDescOnce sync.Once
	file_stubs_grpcc_task_proto_rawDescData = file_stubs_grpcc_task_proto_rawDesc
)

func file_stubs_grpcc_task_proto_rawDescGZIP() []byte {
	file_stubs_grpcc_task_proto_rawDescOnce.Do(func() {
		file_stubs_grpcc_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_stubs_grpcc_task_proto_rawDescData)
	})
	return file_stubs_grpcc_task_proto_rawDescData
}

var file_stubs_grpcc_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stubs_grpcc_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stubs_grpcc_task_proto_goTypes = []interface{}{
	(Priority)(0),       // 0: grpcc.Priority
	(Result)(0),         // 1: grpcc.Result
	(*Create_Task)(nil), // 2: grpcc.Create_Task
	(*Delete_Task)(nil), // 3: grpcc.Delete_Task
	(*View_Task)(nil),   // 4: grpcc.View_Task
	(*Status)(nil),      // 5: grpcc.Status
}
var file_stubs_grpcc_task_proto_depIdxs = []int32{
	0, // 0: grpcc.Create_Task.level_work:type_name -> grpcc.Priority
	2, // 1: grpcc.View_Task.view_task:type_name -> grpcc.Create_Task
	1, // 2: grpcc.Status.result:type_name -> grpcc.Result
	2, // 3: grpcc.Task_Add.Add:input_type -> grpcc.Create_Task
	3, // 4: grpcc.Task_Remove.Remove:input_type -> grpcc.Delete_Task
	4, // 5: grpcc.List_Tasks.List:input_type -> grpcc.View_Task
	5, // 6: grpcc.Task_Add.Add:output_type -> grpcc.Status
	5, // 7: grpcc.Task_Remove.Remove:output_type -> grpcc.Status
	4, // 8: grpcc.List_Tasks.List:output_type -> grpcc.View_Task
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stubs_grpcc_task_proto_init() }
func file_stubs_grpcc_task_proto_init() {
	if File_stubs_grpcc_task_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stubs_grpcc_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Create_Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stubs_grpcc_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete_Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stubs_grpcc_task_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*View_Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stubs_grpcc_task_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stubs_grpcc_task_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_stubs_grpcc_task_proto_goTypes,
		DependencyIndexes: file_stubs_grpcc_task_proto_depIdxs,
		EnumInfos:         file_stubs_grpcc_task_proto_enumTypes,
		MessageInfos:      file_stubs_grpcc_task_proto_msgTypes,
	}.Build()
	File_stubs_grpcc_task_proto = out.File
	file_stubs_grpcc_task_proto_rawDesc = nil
	file_stubs_grpcc_task_proto_goTypes = nil
	file_stubs_grpcc_task_proto_depIdxs = nil
}
